In [ ]:
#cargamos las librerias que utilizamos
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Importamos los datos

datos = pd.read_csv('/content/Churn_Modelling.csv')
#eliminamos las columnas que no utilizamos
#del datos['RowNumber']
#del datos['CustomerId']

datos.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
# nos quedamos con el las variables del 3 al 13 en X(eliminando las columnas 0,1 y 2),
# y con la 13 como variable dependiente
X = datos.iloc[:, 3:13].values
y = datos.iloc[:, 13].values



array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   
    remainder='passthrough'                        
)
X = onehotencoder.fit_transform(X)
X = X[:, 1:]


In [ ]:
#Dividimos los datos en train y test, ademas escalamos los datos

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()

#añadimos la primera capa
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  
                     activation = "relu", input_dim = 11))


In [ ]:
#añadimos la 2 capa

classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))



In [ ]:
#añadimos la 3 capa y finalmente compilamos

classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

#compilamos

classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [ ]:
#ajustamos el RNA al conjunto de entrenamiento

classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)

Epoch 1/100
700/700 [==============================] - 3s 3ms/step - loss: 0.4967 - accuracy: 0.7967
Epoch 2/100
700/700 [==============================] - 2s 3ms/step - loss: 0.4281 - accuracy: 0.7977
Epoch 3/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.8056
Epoch 4/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4167 - accuracy: 0.8231
Epoch 5/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4118 - accuracy: 0.8301
Epoch 6/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4092 - accuracy: 0.8336
Epoch 7/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4070 - accuracy: 0.8333
Epoch 8/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4047 - accuracy: 0.8337
Epoch 9/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4034 - accuracy: 0.8336
Epoch 10/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4024 - accura

In [ ]:
#finalmente evaluamos el modelo con una matriz de confusion

y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
#realizamos una matriz de confusion para ver que tan bueno es el modelo
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
pd.DataFrame(cm)

0    1
0  2267  112
1   359  262

Redes Neuronales aplicadas a los datos de salud materna


In [ ]:
salud = pd.read_csv('/content/Maternal_Health_Risk_Data_Set.csv')
del salud['Unnamed: 0']
salud.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          1
1   35         140           90  13.0      98.0         70          1
2   29          90           70   8.0     100.0         80          1
3   30         140           85   7.0      98.0         70          1
4   35         120           60   6.1      98.0         76          0

In [ ]:
#nos quedamos en X con las variables, Age,SystolicBP,	DiastolicBP,	BS,	BodyTemp,	HeartRate, mientras que en Y
# nos quedamos con RiskLevel	
X = salud.iloc[:, 0:6].values
y = salud.iloc[:, 6].values


In [ ]:
#dividimos el datasets en entrenamiento y testing.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
#construimos el RNA

import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()
classifier.add(Dense(units = 12, kernel_initializer = "uniform",  
                     activation = "relu", input_dim = 6))


In [ ]:
#anadimos la 2 capa
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))

In [ ]:
#añadimos la capa de salida
classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

In [ ]:
#finalmente compilamos el modelo
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [ ]:
#ajustamos el conjunto de entrenamiento

classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)

Epoch 1/100
71/71 [==============================] - 1s 2ms/step - loss: 0.6854 - accuracy: 0.5698
Epoch 2/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6661 - accuracy: 0.5952
Epoch 3/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6649 - accuracy: 0.5952
Epoch 4/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6623 - accuracy: 0.5952
Epoch 5/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6563 - accuracy: 0.5952
Epoch 6/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6574 - accuracy: 0.5966
Epoch 7/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6450 - accuracy: 0.5952
Epoch 8/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6392 - accuracy: 0.6220
Epoch 9/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6330 - accuracy: 0.6248
Epoch 10/100
71/71 [==============================] - 0s 2ms/step - loss: 0.6262 - accuracy: 0.5980
Epoch 11/

In [ ]:
#prediccion de los resultados
y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

In [ ]:
#realizamos una matriz de confusion para ver que tan bueno es el modelo
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
confusion = pd.DataFrame(cm)
confusion

0    1
0  67   52
1  48  138

In [ ]:
TN=confusion[0][0]
TP=confusion[1][1]
FN=confusion[0][1]
FP=confusion[1][0]
#calculamos la sensibilidad
sens = TP/(TP+FN)
sens


0.7419354838709677

In [ ]:
#calculamos la especificidad
espc_1 = TN/(TN+FP)
espc_1

0.5630252100840336

Red Neuronal con Tensorflow 2xx

In [ ]:
#cargamos los datos
fashion = pd.read_csv('/content/fashion-mnist_train.csv')
fashion.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      2       0       0       0  ...         0         0         0         0
1      9       0       0       0  ...         0         0         0         0
2      6       0       0       0  ...         0         0         0         0
3      0       0       0       0  ...         0         0         0         0
4      3       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [ ]:
# nos quedamos con el las variables del 3 al 13 en X(eliminando las columnas 0,1 y 2),
# y con la 13 como variable dependiente
X = fashion.iloc[:, 1:785].values
y = fashion.iloc[:, 0].values
y


array([2, 9, 6, ..., 8, 8, 7])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
X_train = X_train / 255.0
X_test = X_test / 255.0


In [ ]:
#redimensionamos el data
X_train = X_train.reshape(-1, 28*28)
X_train.shape

(42000, 784)

In [ ]:
#redimensionamos tambien el testing
#Redimensionamos el conjunto de testing del mismo modo
X_test = X_test.reshape(-1, 28*28)

In [ ]:
import numpy as np
import datetime
import tensorflow as tf
model = tf.keras.models.Sequential()

In [ ]:
#agregamos la primera capa
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))

In [ ]:
model.add(tf.keras.layers.Dropout(0.2))

In [ ]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [ ]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 128)               100480    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_26 (Dense)            (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#entrenamos el modelo

model.fit(X_train, y_train, epochs=9)

Epoch 1/9
1313/1313 [==============================] - 6s 4ms/step - loss: 0.5757 - sparse_categorical_accuracy: 0.7966
Epoch 2/9
1313/1313 [==============================] - 6s 5ms/step - loss: 0.4304 - sparse_categorical_accuracy: 0.8450
Epoch 3/9
1313/1313 [==============================] - 5s 3ms/step - loss: 0.3926 - sparse_categorical_accuracy: 0.8581
Epoch 4/9
1313/1313 [==============================] - 4s 3ms/step - loss: 0.3668 - sparse_categorical_accuracy: 0.8665
Epoch 5/9
1313/1313 [==============================] - 5s 3ms/step - loss: 0.3512 - sparse_categorical_accuracy: 0.8706
Epoch 6/9
1313/1313 [==============================] - 4s 3ms/step - loss: 0.3361 - sparse_categorical_accuracy: 0.8751
Epoch 7/9
1313/1313 [==============================] - 5s 4ms/step - loss: 0.3254 - sparse_categorical_accuracy: 0.8802
Epoch 8/9
1313/1313 [==============================] - 5s 4ms/step - loss: 0.3171 - sparse_categorical_accuracy: 0.8825
Epoch 9/9
1313/1313 [===================

In [ ]:
#calculamos la prediccion del modelo
test_loss, test_accuracy = model.evaluate(X_test, y_test)

563/563 [==============================] - 3s 4ms/step - loss: 0.3415 - sparse_categorical_accuracy: 0.8804


In [ ]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.8804444670677185


In [ ]:
model_json = model.to_json()
with open("fashion_model.json", "w") as json_file:
    json_file.write(model_json)

In [ ]:
model_json

'{"class_name": "Sequential", "config": {"name": "sequential_11", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 784], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_25_input"}}, {"class_name": "Dense", "config": {"name": "dense_25", "trainable": true, "batch_input_shape": [null, 784], "dtype": "float32", "units": 128, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", "config": {"name": "dense_26", "trainable": true, "dtype": "float32", "units": 10, "activation": "softmax", "use_bias": true, "kernel_in